# **Topic- Types of Flower prediction based on the length and width of the sepal and petal using IRIS dataset**

Import libraries 

In [ ]:

import pandas as pd
import numpy as np

**Now we will explore the dataset:**
The data we will use for this example is the Iris dataset(load_iris), a classical dataset in machine learning and statistics. It is included
in scikit-learn in the datasets module. We can load it by calling the load_iris function:


In [ ]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()#here the data we have downloaded from load_iris is in the form of dictonaries means have keys and values

In [ ]:
print("Keys of iris dataset: \n{}".format(iris_dataset.keys()))

Keys of iris dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


To see the description of the datatset of the key 'DESCR'

In [ ]:
print(iris_dataset['DESCR'][:193]+"\n")
'''OR
you can use the code:
val=iris_DATASET['DESCR']
start_value=value[:200]
print(start_val+"\n")
'''

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre



'OR\nyou can use the code:\nval=iris_DATASET[\'DESCR\']\nstart_value=value[:200]\nprint(start_val+"\n")\n'

Now look in the 'Target' key of the dataset

In [ ]:
print("Target Name:{}".format(iris_dataset['target_names']))
#name of the flowers

Target Name:['setosa' 'versicolor' 'virginica']


Now let's see in feature_names

In [ ]:
print("Features Name:{}".format(iris_dataset['feature_names']))
#name of the features on which we tell which type of flower is it

Features Name:['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Now come to 'data' key of the dataset

In [ ]:
print("Type of Data:{}".format(type(iris_dataset['data'])))
#in this rows corresponds to flowers and columns represent four features which we give to predict the type of flower
print("Shape of the Data:{}".format(iris_dataset['data'].shape))

Type of Data:<class 'numpy.ndarray'>
Shape of the Data:(150, 4)


Feature values for first five samples

In [ ]:
print("First five columns of the data:\n{}".format(iris_dataset['data'][:5]))

First five columns of the data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


now see the 'target' key of the dataset

In [ ]:
print("Type of Target:{}".format(type(iris_dataset['target'])))
#in this target is a 1D array
print("Shape of the Target:{}".format(iris_dataset['target'].shape))

Type of Target:<class 'numpy.ndarray'>
Shape of the Target:(150,)


In [ ]:
print("Target:{}".format(iris_dataset['target']))
#in this the types of flowers are store as integer:0(setosa),1(versicolor),2(virginica)

Target:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


**Test and train the Data**

In [ ]:
from sklearn.model_selection import train_test_split #to split the data into 75% for training and 25% for test
X_train,X_test,y_train,y_test=train_test_split(
    iris_dataset['data'],iris_dataset['target'],random_state=0
)

Before making the split. the train_test_split function shuffles the dataset using a pseudorandom number generator To
make sure that we will get the same output if we run the same function several times, we provide the pseudorandom
number generator with a fixed seed using the random_state parameter.


In [ ]:
print("X_train shape:{}".format(X_train.shape))
print("y_train shape:{}".format(y_train.shape))
print("X_test shape:{}".format(X_test.shape))
print("X_test shape:{}".format(X_test.shape))

X_train shape:(112, 4)
y_train shape:(112,)
X_test shape:(38, 4)
X_test shape:(38, 4)


**Make a ML Model**

here we use algorithm K-nearest neighbour 

In [ ]:
#create the model
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

In [ ]:
#train the model
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**predicting using knn model**

In [ ]:
# a sepal length of 9 cm, a petal length of 1 cm, and a petal width of 0.2 cm.
#What species of iris would this be?
X_new=np.array([[5,2.9,1,0.2]])
print("X_new shape:{}".format(X_new.shape))
'''
We can put this data into a NumPy array, again by calculating the shape—that is, the number of
samples (I ) multiplied by the number of features (4):
'''

X_new shape:(1, 4)


In [ ]:
#predict the given data using predict method
prediction=knn.predict(X_new)
print("Prediction:{}".format(prediction))
print("Prediction target name:{}".format(iris_dataset['target_names'][prediction]))

Prediction:[0]
Prediction target name:['setosa']


**Evaluating the model**

In [ ]:
y_pred=knn.predict(X_test)
print("Test set predictions:\n{}".format(y_pred))

Test set predictions:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [ ]:
print("Test set score:{}".format(np.mean(y_pred==y_test)))

Test set score:0.9736842105263158


# Lets give new value and predict that type also

In [ ]:
X_new=np.array([[3,1.5,5,0.5]])
print("X_new shape:{}".format(X_new.shape))
prediction=knn.predict(X_new)
print("Prediction:{}".format(prediction))
print("Prediction target name:{}".format(iris_dataset['target_names'][prediction]))

X_new shape:(1, 4)
Prediction:[2]
Prediction target name:['virginica']
